"""initial_tables

Revision ID: ab362575a86c
Revises: 
Create Date: 2026-05-10 14:19:00.168201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ab362575a86c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('uploaded_file_path', sa.String(length=512), nullable=True),
    sa.Column('uploaded_file_name', sa.String(length=256), nullable=True),
    sa.Column('uploaded_file_type', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('suppliers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('supported_states', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('supported_material_types', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('supported_opening_types', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('supported_window_materials', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('supported_glass_types', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('min_width', sa.Float(), nullable=True),
    sa.Column('max_width', sa.Float(), nullable=True),
    sa.Column('min_height', sa.Float(), nullable=True),
    sa.Column('max_height', sa.Float(), nullable=True),
    sa.Column('base_unit_price', sa.Float(), nullable=False),
    sa.Column('lead_time_days', sa.Integer(), nullable=False),
    sa.Column('reliability_score', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('progress_steps',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_info',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('project_name', sa.String(length=256), nullable=True),
    sa.Column('site_address', sa.String(length=512), nullable=True),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.Column('state', sa.String(length=64), nullable=True),
    sa.Column('zip_code', sa.String(length=16), nullable=True),
    sa.Column('detected_file_type', sa.String(length=64), nullable=True),
    sa.Column('detected_relevant_pages', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_table('window_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('tag', sa.String(length=64), nullable=True),
    sa.Column('material_type', sa.String(length=64), nullable=False),
    sa.Column('width', sa.String(length=64), nullable=True),
    sa.Column('height', sa.String(length=64), nullable=True),
    sa.Column('area', sa.String(length=64), nullable=True),
    sa.Column('quantity', sa.String(length=32), nullable=True),
    sa.Column('opening_type', sa.String(length=128), nullable=True),
    sa.Column('material', sa.String(length=128), nullable=True),
    sa.Column('u_value', sa.String(length=32), nullable=True),
    sa.Column('shgc', sa.String(length=32), nullable=True),
    sa.Column('vt', sa.String(length=32), nullable=True),
    sa.Column('glass_type', sa.String(length=128), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('original_extraction', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('user_edits', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recommendations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('window_item_id', sa.String(length=36), nullable=False),
    sa.Column('supplier_id', sa.String(length=36), nullable=False),
    sa.Column('tag', sa.String(length=64), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('estimated_total', sa.Float(), nullable=False),
    sa.Column('lead_time_days', sa.Integer(), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=False),
    sa.Column('match_reason', sa.Text(), nullable=True),
    sa.Column('risk_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.ForeignKeyConstraint(['window_item_id'], ['window_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recommendations')
    op.drop_table('window_items')
    op.drop_table('project_info')
    op.drop_table('progress_steps')
    op.drop_table('suppliers')
    op.drop_table('sessions')
    # ### end Alembic commands ###
