"""LLM step 2: final window-schedule extraction.

Prompt and request shape preserved verbatim from NOTEBOOKS/pdf_algo_test.py.
"""

from __future__ import annotations

import json
from dataclasses import asdict
from typing import Dict, List

from app.services.extraction.pdf._helpers import log_debug, log_section
from app.services.extraction.pdf.config import PDFExtractionConfig
from app.services.extraction.pdf.llm_client import LangChainLLMClient
from app.services.extraction.pdf.models import (
    CropPlanDebug,
    CropRender,
    LLMPageResult,
    PageAnalysis,
    RenderedPage,
)
from app.services.extraction.pdf.schemas import ExtractionPageResponse


def build_extraction_prompt(
    page_analysis: PageAnalysis,
    crop_plan: CropPlanDebug | None,
    crop_renders: List[CropRender],
) -> str:
    native_text = page_analysis.text or ""
    max_native_chars = 60000
    if len(native_text) > max_native_chars:
        native_text = native_text[:max_native_chars] + "\n\n[TRUNCATED: native text exceeded cap]"

    deterministic_debug = {
        "page_number": page_analysis.page_number,
        "title_source": page_analysis.title_source,
        "outline_titles": page_analysis.outline_titles,
        "heuristic_titles": page_analysis.heuristic_titles,
        "title_candidates": page_analysis.title_candidates,
        "sheet_number_candidates": page_analysis.sheet_number_candidates,
        "title_score": page_analysis.title_score,
        "native_text_score": page_analysis.native_text_score,
        "final_score": page_analysis.final_score,
        "selection_reason": page_analysis.selection_reason,
        "positive_signals": page_analysis.positive_signals,
        "negative_signals": page_analysis.negative_signals,
    }

    crop_debug = asdict(crop_plan) if crop_plan else None
    crop_render_debug = [
        {
            "crop_index": c.crop_index,
            "label": c.label,
            "normalized_bbox_original": c.normalized_bbox_original,
            "normalized_bbox_expanded": c.normalized_bbox_expanded,
            "confidence": c.confidence,
            "reason": c.reason,
            "png_path": c.png_path,
        }
        for c in crop_renders
    ]

    if crop_renders:
        image_instructions = (
            "Image order:\n"
            "1. The first image is the full page for context.\n"
            "2. The following image(s) are zoomed crop(s) from the same page. "
            "Use the crop images to read small schedule details accurately. "
            "Use the full page for context and to avoid misinterpreting the crop."
        )
    else:
        image_instructions = (
            "Image order:\n"
            "1. The first and only image is the full page. The crop-planning agent judged it readable enough, "
            "or no valid crop was available."
        )

    return f"""
You are an expert construction-document extraction agent for architectural PDFs.

You receive:
1. Native text extracted by PyMuPDF. It may be incomplete, out of order, duplicated, or missing visual table structure.
2. Full-page image, and possibly zoomed crop image(s) generated by a prior crop-planning step.

{image_instructions}

Your task:
A. Decide whether this page contains a window/opening/glazing/fenestration schedule or schedule-like table relevant to windows/openings.
B. If it does, extract ONLY window rows into the normalized Xynect schema.
C. If it does not, return contains_schedule=false and extracted_rows=[].

CRITICAL — WINDOWS ONLY:
- Extract ONLY window, glazing, fenestration, and opening rows.
- COMPLETELY IGNORE any door entries, door rows, or door-only schedules. Do not include them in extracted_rows under any circumstances.
- If a schedule mixes doors and windows, silently skip every door row and extract only the window/glazing rows.
- A door-only schedule should be treated as if the page contains no relevant schedule at all.

Important rules:
- This document may contain typos, OCR errors, or inconsistent formatting. If you detect ambiguity or conflicting information during extraction, use your best judgment to resolve it and record a brief explanation in the notes field for that row.
- Use BOTH native text and images.
- Use crop images for exact small text values if crops are provided.
- Use full-page image for context.
- Do not hallucinate. Extract only values explicitly visible in the native text or images.
- If a field is absent, return an empty string.
- Preserve tag labels exactly as shown, such as W1, W-1, W01, A, B, etc.
- Prefer actual schedule table values over notes, legends, or general specifications.
- Elevation pages are usually not schedule pages. Only extract from an elevation if it clearly contains tabular window/opening schedule information.
- Width/height may appear as FT/IN, inches, feet, or architectural notation. Preserve the visible representation.
- Quantity may be shown as QTY, COUNT, NO., or repeated tag rows. Extract explicit quantity only. Do not count windows from drawings.
- U-value may also appear as U-factor. Map it to u_value.
- SHGC, VT, glass type, frame/material, opening type should be extracted when explicitly available.
- Area can be extracted if explicitly listed, but do not calculate area yourself in this LLM output.
- Confidence should reflect how certain you are that the row values were read correctly.

Classification labels:
- window_schedule
- opening_schedule
- glazing_schedule
- fenestration_schedule
- mixed_door_window_schedule
- door_only_schedule
- elevation_with_window_info
- not_relevant
- unknown

Deterministic pre-analysis:
{json.dumps(deterministic_debug, indent=2)}

Crop planning result:
{json.dumps(crop_debug, indent=2)}

Crop render debug:
{json.dumps(crop_render_debug, indent=2)}

Native text:
--- BEGIN NATIVE TEXT ---
{native_text}
--- END NATIVE TEXT ---
""".strip()


class PDFScheduleExtractor:
    def __init__(self, config: PDFExtractionConfig, llm_client: LangChainLLMClient):
        self.config = config
        self.llm = llm_client

    def extract(
        self,
        selected_pages: List[PageAnalysis],
        rendered_pages: List[RenderedPage],
        crop_plans: List[CropPlanDebug],
        crop_renders: List[CropRender],
    ) -> List[LLMPageResult]:
        log_section("6. LangChain final extraction")

        structured_llm = self.llm.with_structured_output(ExtractionPageResponse)

        rendered_by_page_index = {rp.page_index: rp for rp in rendered_pages}
        crop_plan_by_page = {cp.page_number: cp for cp in crop_plans}
        crops_by_page: Dict[int, List[CropRender]] = {}
        for crop in crop_renders:
            crops_by_page.setdefault(crop.page_number, []).append(crop)

        results: List[LLMPageResult] = []

        for page_analysis in selected_pages:
            crop_plan = crop_plan_by_page.get(page_analysis.page_number)

            if crop_plan and not crop_plan.contains_schedule:
                log_debug(
                    f"Skipping final extraction page {page_analysis.page_number}: crop planner says not schedule page."
                )
                results.append(
                    LLMPageResult(
                        page_number=page_analysis.page_number,
                        contains_schedule=False,
                        schedule_type=crop_plan.schedule_type,
                        confidence=crop_plan.confidence,
                        reason=f"Skipped by crop planner: {crop_plan.reason}",
                        extracted_rows=[],
                        warnings=crop_plan.warnings,
                        raw_response=asdict(crop_plan),
                    )
                )
                continue

            rendered = rendered_by_page_index[page_analysis.page_index]
            page_crops = crops_by_page.get(page_analysis.page_number, [])

            prompt = build_extraction_prompt(page_analysis, crop_plan, page_crops)
            image_uris = [rendered.data_uri] + [crop.data_uri for crop in page_crops]

            log_debug(
                f"Final extraction page {page_analysis.page_number}: "
                f"full_page=1, crops={len(page_crops)}, model={self.llm.model_name}"
            )

            response: ExtractionPageResponse = self.llm.invoke_multimodal(
                structured_llm=structured_llm,
                prompt=prompt,
                image_data_uris=image_uris,
            )

            parsed_rows = [row.model_dump() for row in response.extracted_rows]
            classification = response.page_classification

            result = LLMPageResult(
                page_number=response.page_number,
                contains_schedule=classification.contains_schedule,
                schedule_type=classification.schedule_type,
                confidence=classification.confidence,
                reason=classification.reason,
                extracted_rows=parsed_rows,
                warnings=response.warnings,
                raw_response=response.model_dump(),
            )
            results.append(result)

            log_debug(
                f"Extraction result page {result.page_number}: contains_schedule={result.contains_schedule}, "
                f"schedule_type={result.schedule_type}, confidence={result.confidence}, rows={len(result.extracted_rows)}"
            )
            log_debug(f"  reason={result.reason}")
            if result.warnings:
                log_debug(f"  warnings={result.warnings}")

        return results
